spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/lomba
    username: postgres 
    password:
    
  dao:
    exceptiontranslation:
      enabled: true

logging:
  level:
    web: INFO
    '[net.ttddyy.dsproxy.listener]': debug