spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/lomba
    username: postgres 
    password:
    
  dao:
    exceptiontranslation:
      enabled: true
      
server:
  error:
    whitelabel:
      enabled: false
      
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - health
        - info
        - env
        - auditevents
        - beans
        - conditions
        - configprops
        - liquibase
        - metrics
        - startup
        - mappings
  auditevents:
    enabled: true

logging:
  level:
    web: DEBUG
    '[net.ttddyy.dsproxy.listener]': debug
  